# This is a basic workflow that is manually triggered

name: Deployment workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Checkout your codebase
    
    - name: Setup Node.js
      uses: actions/setup-node@v3  # Sets up Node.js (you can specify the version)
      with:
        node-version: '18'  # Or the Node.js version you require
    
    - name: Install Dependencies
      run: cd frontend && npm install  # Install all dependencies
    
    - name: Set Permissions
      run: cd frontend && chmod +x deploy.sh  # Set executable permissions for your script
    
    - name: Deploy
      env: 
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: cd frontend && ./deploy.sh  # Deploy your app
      
