jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Print Working Directory
      run: pwd  # This shows the current directory

    - name: List Files
      run: ls -la frontend  # List all files in 'frontend' to ensure deploy.sh is there

    - name: Change Directory and Set Permissions
      run: cd frontend && chmod +x deploy.sh
      
    - name: Deploy
      run: cd frontend && ./deploy.sh
